development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: paredao_bbb_dev
  pool: 5
  username:
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: paredao_bbb_test
  pool: 5
  username:
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: paredao_bbb_production
  pool: 20
  username:
  password:
  socket: /var/run/mysqld/mysqld.sock
